import os
from dotenv import load_dotenv

load_dotenv()

DEFAULT_SYSTEM_TEXT = """
"""

SYSTEM_TEXT = os.environ.get("OPENAI_SYSTEM_TEXT", DEFAULT_SYSTEM_TEXT)

DEFAULT_OPENAI_TIMEOUT_SECONDS = 30
OPENAI_TIMEOUT_SECONDS = int(
    os.environ.get("OPENAI_TIMEOUT_SECONDS", DEFAULT_OPENAI_TIMEOUT_SECONDS)
)

DEFAULT_OPENAI_MODEL = "gpt-4"
OPENAI_MODEL = os.environ.get("OPENAI_MODEL", DEFAULT_OPENAI_MODEL)

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")

USE_SLACK_LANGUAGE = os.environ.get("USE_SLACK_LANGUAGE", "true") == "true"

SLACK_APP_LOG_LEVEL = os.environ.get("SLACK_APP_LOG_LEVEL", "DEBUG")

TRANSLATE_MARKDOWN = os.environ.get("TRANSLATE_MARKDOWN", "false") == "true"

PINCONE_API_KEY = os.environ["PINECONE_API_KEY"]
PINECONE_ENV = os.environ["PINECONE_ENV"]
VECTOR_INDEX_NAME = os.environ["VECTOR_INDEX_NAME"]


ZILLIZ_CLOUD_URI = os.environ["ZILLIZ_CLOUD_URI"]
ZILLIZ_CLOUD_API_KEY = os.environ["ZILLIZ_CLOUD_API_KEY"]

VECTOR_STORE = os.environ["VECTOR_STORE"]
